const { Model, DataTypes } = require("sequelize");
const sequelize = require("./dbconfig");
const Photo = require("./photo");

class Gallery extends Model {}

Gallery.init(
  {
    // Model attributes are defined here
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    description: {
      type: DataTypes.TEXT,
    },
  },
  {
    // Other model options go here
    sequelize, // pass the connection instance
    modelName: "gallery",
    // do we want timestamps here? they're autogenerated
    // timestamps: false,
  }
);

Gallery.hasMany(Photo);

module.exports = Gallery;
